<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <PackageJsonName Condition="$(PackageJsonName) == ''">liberationfleet.client</PackageJsonName>
    <PackageJsonVersion Condition="$(PackageJsonVersion) == ''">0.0.0</PackageJsonVersion>
    <PackageJsonScriptsNg Condition="$(PackageJsonScriptsNg) == ''">ng</PackageJsonScriptsNg>
    <PackageJsonScriptsStart Condition="$(PackageJsonScriptsStart) == ''">run-script-os</PackageJsonScriptsStart>
    <PackageJsonScriptsBuild Condition="$(PackageJsonScriptsBuild) == ''">ng build</PackageJsonScriptsBuild>
    <PackageJsonScriptsBuildNative Condition="$(PackageJsonScriptsBuildNative) == ''">ng build --configuration native</PackageJsonScriptsBuildNative>
    <PackageJsonScriptsCapSync Condition="$(PackageJsonScriptsCapSync) == ''">npm run build:native &amp;&amp; npx cap sync</PackageJsonScriptsCapSync>
    <PackageJsonScriptsCapAndroid Condition="$(PackageJsonScriptsCapAndroid) == ''">npm run cap:sync &amp;&amp; npx cap open android</PackageJsonScriptsCapAndroid>
    <PackageJsonScriptsCapIos Condition="$(PackageJsonScriptsCapIos) == ''">npm run cap:sync &amp;&amp; npx cap open ios</PackageJsonScriptsCapIos>
    <PackageJsonScriptsCapAddAndroid Condition="$(PackageJsonScriptsCapAddAndroid) == ''">npx cap add android</PackageJsonScriptsCapAddAndroid>
    <PackageJsonScriptsCapAddIos Condition="$(PackageJsonScriptsCapAddIos) == ''">npx cap add ios</PackageJsonScriptsCapAddIos>
    <PackageJsonScriptsWatch Condition="$(PackageJsonScriptsWatch) == ''">ng build --watch --configuration development</PackageJsonScriptsWatch>
    <PackageJsonScriptsTest Condition="$(PackageJsonScriptsTest) == ''">ng test</PackageJsonScriptsTest>
    <PackageJsonScriptsTestCi Condition="$(PackageJsonScriptsTestCi) == ''">ng test --watch=false --browsers=ChromeHeadless</PackageJsonScriptsTestCi>
    <PackageJsonScriptsPrestart Condition="$(PackageJsonScriptsPrestart) == ''">node aspnetcore-https</PackageJsonScriptsPrestart>
    <PackageJsonScriptsStartWindows Condition="$(PackageJsonScriptsStartWindows) == ''">ng serve --ssl --ssl-cert "%APPDATA%\ASP.NET\https\%npm_package_name%.pem" --ssl-key "%APPDATA%\ASP.NET\https\%npm_package_name%.key"</PackageJsonScriptsStartWindows>
    <PackageJsonScriptsStartDefault Condition="$(PackageJsonScriptsStartDefault) == ''">ng serve --ssl --ssl-cert "$HOME/.aspnet/https/${npm_package_name}.pem" --ssl-key "$HOME/.aspnet/https/${npm_package_name}.key"</PackageJsonScriptsStartDefault>
    <PackageJsonPrivate Condition="$(PackageJsonPrivate) == ''">true</PackageJsonPrivate>
    <PackageJsonDependenciesAngularAnimations Condition="$(PackageJsonDependenciesAngularAnimations) == ''">17.3.12</PackageJsonDependenciesAngularAnimations>
    <PackageJsonDependenciesAngularCdk Condition="$(PackageJsonDependenciesAngularCdk) == ''">17.3.10</PackageJsonDependenciesAngularCdk>
    <PackageJsonDependenciesAngularCommon Condition="$(PackageJsonDependenciesAngularCommon) == ''">17.3.12</PackageJsonDependenciesAngularCommon>
    <PackageJsonDependenciesAngularCompiler Condition="$(PackageJsonDependenciesAngularCompiler) == ''">17.3.12</PackageJsonDependenciesAngularCompiler>
    <PackageJsonDependenciesAngularCore Condition="$(PackageJsonDependenciesAngularCore) == ''">17.3.12</PackageJsonDependenciesAngularCore>
    <PackageJsonDependenciesAngularForms Condition="$(PackageJsonDependenciesAngularForms) == ''">17.3.12</PackageJsonDependenciesAngularForms>
    <PackageJsonDependenciesAngularPlatformBrowser Condition="$(PackageJsonDependenciesAngularPlatformBrowser) == ''">17.3.12</PackageJsonDependenciesAngularPlatformBrowser>
    <PackageJsonDependenciesAngularPlatformBrowserDynamic Condition="$(PackageJsonDependenciesAngularPlatformBrowserDynamic) == ''">17.3.12</PackageJsonDependenciesAngularPlatformBrowserDynamic>
    <PackageJsonDependenciesAngularRouter Condition="$(PackageJsonDependenciesAngularRouter) == ''">17.3.12</PackageJsonDependenciesAngularRouter>
    <PackageJsonDependenciesCapacitorAndroid Condition="$(PackageJsonDependenciesCapacitorAndroid) == ''">6.2.0</PackageJsonDependenciesCapacitorAndroid>
    <PackageJsonDependenciesCapacitorApp Condition="$(PackageJsonDependenciesCapacitorApp) == ''">6.0.2</PackageJsonDependenciesCapacitorApp>
    <PackageJsonDependenciesCapacitorCore Condition="$(PackageJsonDependenciesCapacitorCore) == ''">6.2.0</PackageJsonDependenciesCapacitorCore>
    <PackageJsonDependenciesCapacitorFilesystem Condition="$(PackageJsonDependenciesCapacitorFilesystem) == ''">6.0.2</PackageJsonDependenciesCapacitorFilesystem>
    <PackageJsonDependenciesCapacitorIos Condition="$(PackageJsonDependenciesCapacitorIos) == ''">6.2.0</PackageJsonDependenciesCapacitorIos>
    <PackageJsonDependenciesCapacitorKeyboard Condition="$(PackageJsonDependenciesCapacitorKeyboard) == ''">6.0.3</PackageJsonDependenciesCapacitorKeyboard>
    <PackageJsonDependenciesCapacitorSplashScreen Condition="$(PackageJsonDependenciesCapacitorSplashScreen) == ''">6.0.3</PackageJsonDependenciesCapacitorSplashScreen>
    <PackageJsonDependenciesCapacitorStatusBar Condition="$(PackageJsonDependenciesCapacitorStatusBar) == ''">6.0.2</PackageJsonDependenciesCapacitorStatusBar>
    <PackageJsonDependenciesFortawesomeFontawesomeFree Condition="$(PackageJsonDependenciesFortawesomeFontawesomeFree) == ''">7.2.0</PackageJsonDependenciesFortawesomeFontawesomeFree>
    <PackageJsonDependenciesHonemNativeVideoCompressor Condition="$(PackageJsonDependenciesHonemNativeVideoCompressor) == ''">0.2.3</PackageJsonDependenciesHonemNativeVideoCompressor>
    <PackageJsonDependenciesMicrosoftSignalr Condition="$(PackageJsonDependenciesMicrosoftSignalr) == ''">8.0.7</PackageJsonDependenciesMicrosoftSignalr>
    <PackageJsonDependenciesCapacitorBlobWriter Condition="$(PackageJsonDependenciesCapacitorBlobWriter) == ''">1.1.20</PackageJsonDependenciesCapacitorBlobWriter>
    <PackageJsonDependenciesJestEditorSupport Condition="$(PackageJsonDependenciesJestEditorSupport) == ''">32.0.0-beta.1</PackageJsonDependenciesJestEditorSupport>
    <PackageJsonDependenciesLivekitClient Condition="$(PackageJsonDependenciesLivekitClient) == ''">2.9.9</PackageJsonDependenciesLivekitClient>
    <PackageJsonDependenciesMediabunny Condition="$(PackageJsonDependenciesMediabunny) == ''">1.52.3</PackageJsonDependenciesMediabunny>
    <PackageJsonDependenciesRunScriptOs Condition="$(PackageJsonDependenciesRunScriptOs) == ''">1.1.6</PackageJsonDependenciesRunScriptOs>
    <PackageJsonDependenciesRxjs Condition="$(PackageJsonDependenciesRxjs) == ''">7.8.2</PackageJsonDependenciesRxjs>
    <PackageJsonDependenciesTslib Condition="$(PackageJsonDependenciesTslib) == ''">2.8.1</PackageJsonDependenciesTslib>
    <PackageJsonDependenciesZoneJs Condition="$(PackageJsonDependenciesZoneJs) == ''">0.14.10</PackageJsonDependenciesZoneJs>
    <PackageJsonDevdependenciesAngularDevkitBuildAngular Condition="$(PackageJsonDevdependenciesAngularDevkitBuildAngular) == ''">17.3.17</PackageJsonDevdependenciesAngularDevkitBuildAngular>
    <PackageJsonDevdependenciesAngularCli Condition="$(PackageJsonDevdependenciesAngularCli) == ''">17.3.17</PackageJsonDevdependenciesAngularCli>
    <PackageJsonDevdependenciesAngularCompilerCli Condition="$(PackageJsonDevdependenciesAngularCompilerCli) == ''">17.3.12</PackageJsonDevdependenciesAngularCompilerCli>
    <PackageJsonDevdependenciesCapacitorCli Condition="$(PackageJsonDevdependenciesCapacitorCli) == ''">6.2.0</PackageJsonDevdependenciesCapacitorCli>
    <PackageJsonDevdependenciesTypesJasmine Condition="$(PackageJsonDevdependenciesTypesJasmine) == ''">5.1.15</PackageJsonDevdependenciesTypesJasmine>
    <PackageJsonDevdependenciesJasmineCore Condition="$(PackageJsonDevdependenciesJasmineCore) == ''">5.1.2</PackageJsonDevdependenciesJasmineCore>
    <PackageJsonDevdependenciesKarma Condition="$(PackageJsonDevdependenciesKarma) == ''">6.4.4</PackageJsonDevdependenciesKarma>
    <PackageJsonDevdependenciesKarmaChromeLauncher Condition="$(PackageJsonDevdependenciesKarmaChromeLauncher) == ''">3.2.0</PackageJsonDevdependenciesKarmaChromeLauncher>
    <PackageJsonDevdependenciesKarmaCoverage Condition="$(PackageJsonDevdependenciesKarmaCoverage) == ''">2.2.1</PackageJsonDevdependenciesKarmaCoverage>
    <PackageJsonDevdependenciesKarmaJasmine Condition="$(PackageJsonDevdependenciesKarmaJasmine) == ''">5.1.0</PackageJsonDevdependenciesKarmaJasmine>
    <PackageJsonDevdependenciesKarmaJasmineHtmlReporter Condition="$(PackageJsonDevdependenciesKarmaJasmineHtmlReporter) == ''">2.1.0</PackageJsonDevdependenciesKarmaJasmineHtmlReporter>
    <PackageJsonDevdependenciesTypescript Condition="$(PackageJsonDevdependenciesTypescript) == ''">5.3.3</PackageJsonDevdependenciesTypescript>
  </PropertyGroup>
</Project>